# Diccionario de colores
color = {
    "celeste_claro": "#B4E0FF",
    "rojo_claro": "#FFCBCB",
    "celeste_oscuro": "#003E67",
    "beige": "#A5A55F",
    "beige_resaltado": "#B7B78A",
    "blanco": "#FFFFFF",
    "negro": "#000000",
    "negro_resaltado": "#242424",
    "gris": "#AAAAAA",
    "rojo_anaranjado": "#FF3C00",
    "rojo": "#FF0000",
    "rojo_resaltado": "#FF5A5A",
    "amarillo": "#FFFB00",
    "amarillo_resaltado": "#FFFC4C",
    "verde": "#00FF00",
    "verde_resaltado":"#8AFF7B",
    "azul_violáceo": "#3D00CA",
    "azul_violáceo_resaltado": "#5F30CB",
    "azul": "#000DFF",
    "azul_resaltado": "#6C73FF",
    "naranja": "#FF7300",
    "naranja_resaltado": "#FFC16A",
    "violeta": "#9D00FF",
    "violeta_resaltado": "#CD7BFF",
    "verde_oscuro": "#007800",
    "verde_claro": "#A7FFA7",
}
